# Generated by Django 4.2 on 2023-xx-xx xx:xx
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_social_account',
            field=models.BooleanField(default=False),
        ),
    ]