# Generated by Django 5.1.15 on 2026-01-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
        ('users', '0002_user_is_social_account'),
    ]

    operations = [
    ]
